### ISSUE TITLE
"LLM Provider NOT provided" Error for Non-OpenAI Models in Litellm

### ISSUE THREAD

**Issue by dhirenmathur** [potpie-ai/potpie#156]
Description: CrewAI uses the Litellm library to route LLM requests to the appropriate model. Currently, Litellm throws an error, "LLM Provider NOT provided", whenever a request is made for a non-OpenAI model, preventing proper routing to other providers.

Expected Behavior: Litellm should handle non-OpenAI models without throwing an error, allowing CrewAI to route requests to the correct LLM as specified.

Steps to Reproduce:

* Configure CrewAI to use a non-OpenAI LLM provider through Litellm using the following API: 
```
curl -X POST "http://localhost:8001/api/v1/set-global-ai-provider/" \
-H "Authorization: Bearer <API_TOKEN>" \
-H "Content-Type: application/json" \
-d '{
  "provider": "anthropic"
}'
```
* Set the anthropic API key "ANTHROPIC_API_KEY" in your .env 
* Create a conversation: 
```
curl -X 'POST' \
  'http://localhost:8001/api/v1/conversations/' \
  -H 'accept: application/json' \
  -H 'Content-Type: application/json' \
  -d '{
  "user_id": "your_user_id",
  "title": "Conversation Title",
  "status": "active",
  "project_ids": [
    "project_id"
  ],
  "agent_ids": [
    "codebase_qna_agent"
  ]
}'
```
* Send message: 
```
curl -X 'POST' \
  'http://localhost:8001/api/v1/conversations/1234/message/' \
  -H 'accept: application/json' \
  -H 'Content-Type: application/json' \
  -d '{
  "content": "Your message content here",
  "node_ids": [
    {
      "node_id": "node_identifier",
      "name": "node_name"
    }
  ]
}'
```

**Comment by palash018** [comment]
I will try to reproduce this issue, currently facing some issues regarding running code on wsl.

**Comment by palash018** [comment]
![image](https://github.com/user-attachments/assets/83fe4a3d-38dc-413b-bdec-dd061e39478c)
some kind of connection error

**Comment by dhirenmathur** [comment]
Not a known issue @palash018 , is this a blocker or were you able to proceed with the task?

**Comment by palash018** [comment]
@dhirenmathur it is actually a blocker since I cannot even run the code itself due to this issue. issue presents itself in ```./start.sh``` itself

**Comment by dhirenmathur** [comment]
Got it, I'll try to reproduce and get back to you

**Comment by vineetshar** [comment]
Fixed today, can be closed @dhirenmathur

**Comment by dhirenmathur** [comment]
Yes, let's close it
