### ISSUE TITLE
Implement Comprehensive Development Mode 

### ISSUE THREAD

**Issue by dhirenmathur** [potpie-ai/potpie#174]
## Overview
The `isDevelopmentMode` flag is designed to disable third-party services (Firebase, GitHub, Portkey, AgentOps) to enable local development with minimal setup. Several components need to be modified to properly handle this development mode.

## Current Issue
- High time to get started with contribution

### 1. Main Application (`main.py`)
- [ ] Add validation to ensure `isDevelopmentMode` is only enabled when `ENV='development'`
- [ ] Implement error handling for mismatched configurations
- [ ] Add logging for development mode status on startup

### 2. Authentication Service (`auth_service.py`)
- [ ] Prevent Firebase initialization in development mode
- [ ] Implement mock authentication that returns:
  ```python
  {"user_id": os.getenv("defaultUsername")}
  ```
- [ ] Add clear logging when using mock authentication

### 3. Provider Service (`provider_service.py`)
- [ ] Modify ChatOpenAI initialization to bypass Portkey in development mode
- [ ] Modify ChatAnthropic initialization to bypass Portkey in development mode
- [ ] Add configuration validation for both providers
- [ ] Implement logging for provider initialization status

### 4. GitHub Service (`github_service.py`)
- [ ] Prevent GitHub client initialization in development mode
- [ ] Implement local repository operations:
  - [ ] Directory scanning
  - [ ] Local git operations for metadata
  - [ ] File reading capabilities
- [ ] Modify get_code functions to read from neo4j node 'text' key for local repos
- [ ] Add validation for required local repo structure

### 5. Secret Manager
- [ ] Prevent secret manager initialization in development mode
- [ ] Implement local alternative for secrets (env variables)
- [ ] Add validation for required development environment variables

## Documentation Updates Needed
Update teh Getting Started file with - 
- [ ] Development mode setup instructions
- [ ] Local repository requirements
- [ ] Environment variable documentation
- [ ] Troubleshooting guide

## Acceptance Criteria
1. Application starts successfully in development mode with single start.sh file
2. No third-party service initialization occurs in development mode
3. All core functionality works with local alternatives
4. Clear error messages for misconfiguration
5. Comprehensive logging of development mode status

**Comment by waveywaves** [comment]
For the provider is it possible for the user to use a locally hosted model such as something fro huggingface ?

For the GitHub service which focuses on GitHub, it should be possible for users to use their own git server like gittea.

**Comment by dhirenmathur** [comment]
@waveywaves 
>For the provider is it possible for the user to use a locally hosted model such as something fro huggingface ?
We do have support for other local as well as open source models planned as a separate feature. 

>For the GitHub service which focuses on GitHub, it should be possible for users to use their own git server like gittea.
For Github the future integrations will be more along the lines of bitbucket etc which are more widely used 

Do you want to work on this issue?

**Comment by waveywaves** [comment]
yep can you assign me to this issue ?

**Comment by dhirenmathur** [comment]
Let me know if you need any help @waveywaves

**Comment by dhirenmathur** [comment]
@waveywaves were you able to get started?

**Comment by waveywaves** [comment]
Hey @dhirenmathur getting started on it today and plan on working through it tomorrow, I'll update you

**Comment by vineetshar** [comment]
hi @waveywaves I am going to pick up the accommodation for tools / code fetching services for supporting local repos , removing their tight coupling with GitHub as part of another internal improvement. 

you can continue with rest of the implementation.

**Comment by waveywaves** [comment]
@vineetshar sounds good to me

**Comment by waveywaves** [comment]
first PR for this issue 
https://github.com/potpie-ai/potpie/pull/192

**Comment by waveywaves** [comment]
@dhirenmathur we can mark 1,2,3 over here as done

**Comment by vineetshar** [comment]
@waveywaves   1,2,3,4,5 all are done now.

**Comment by waveywaves** [comment]
@vineetshar that's awesome ! Do we still need comprehensive documentation on this ? If so I can contribute to it.
